stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/


      
stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  image: maven:latest
  script:
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/
